"""initial schema

Revision ID: fac07117a8a6
Revises: 
Create Date: 2026-09-03 22:56:44.385418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fac07117a8a6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('competitors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('include_subreddits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exclude_subreddits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('queries_generated', sa.Integer(), nullable=True),
    sa.Column('candidates_fetched', sa.Integer(), nullable=True),
    sa.Column('duplicates_removed', sa.Integer(), nullable=True),
    sa.Column('opportunities_scored', sa.Integer(), nullable=True),
    sa.Column('total_to_score', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_status'), 'scans', ['status'], unique=False)
    op.create_table('opportunities',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('reddit_post_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('subreddit', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('num_comments', sa.Integer(), nullable=True),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('intent_type', sa.String(length=30), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('suggested_angle', sa.Text(), nullable=True),
    sa.Column('what_not_to_do', sa.Text(), nullable=True),
    sa.Column('content_opportunity', sa.Text(), nullable=True),
    sa.Column('llm_raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_priority'), 'opportunities', ['priority'], unique=False)
    op.create_index(op.f('ix_opportunities_project_id'), 'opportunities', ['project_id'], unique=False)
    op.create_index('ix_opportunities_project_priority', 'opportunities', ['project_id', 'priority'], unique=False)
    op.create_index('ix_opportunities_project_status_score', 'opportunities', ['project_id', 'status', 'score'], unique=False)
    op.create_index(op.f('ix_opportunities_reddit_post_id'), 'opportunities', ['reddit_post_id'], unique=True)
    op.create_index(op.f('ix_opportunities_scan_id'), 'opportunities', ['scan_id'], unique=False)
    op.create_index(op.f('ix_opportunities_score'), 'opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_subreddit'), 'opportunities', ['subreddit'], unique=False)
    op.create_table('opportunity_score_breakdowns',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_score_breakdowns_opportunity_id'), 'opportunity_score_breakdowns', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_score_breakdowns_opportunity_id'), table_name='opportunity_score_breakdowns')
    op.drop_table('opportunity_score_breakdowns')
    op.drop_index(op.f('ix_opportunities_subreddit'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_scan_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_reddit_post_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_project_status_score', table_name='opportunities')
    op.drop_index('ix_opportunities_project_priority', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_project_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_priority'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_scans_status'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('projects')
    # ### end Alembic commands ###
